use std::path::{Component, Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Duration;

use anyhow::{Context, Result};

use super::{normalize_relative, GamePlugin, GamePluginInfo};

/// Top-level folders that belong at the Darktide install root (Mod Loader layout).
pub const DARKTIDE_ROOT_DIRS: &[&str] = &["mods", "tools", "binaries", "bundle"];

/// Staging roots that must not be peeled as archive wrappers.
pub const DARKTIDE_PRESERVE_ROOTS: &[&str] = &["mods", "tools", "binaries", "bundle", "dmf"];

/// Folder names that must never appear in `mod_load_order.txt`.
pub const DARKTIDE_LOAD_ORDER_EXCLUDE: &[&str] = &["dmf"];

const PATCHER_TIMEOUT: Duration = Duration::from_secs(60);
const PATCH_MARKER: &[u8] = b"patch_999";

pub struct Warhammer40kDarktidePlugin;

impl GamePlugin for Warhammer40kDarktidePlugin {
    fn info(&self) -> GamePluginInfo {
        GamePluginInfo {
            id: "warhammer40kdarktide",
            display_name: "Warhammer 40,000: Darktide",
            nexus_domain: "warhammer40kdarktide",
            match_names: &[
                "darktide",
                "warhammer 40,000: darktide",
                "warhammer 40k darktide",
                "warhammer40kdarktide",
            ],
        }
    }

    fn prefers_mod_folder(&self) -> bool {
        false
    }

    fn preserve_staging_root_names(&self) -> &[&str] {
        DARKTIDE_PRESERVE_ROOTS
    }

    fn should_wrap_as_mod_folder(&self, content_root: &Path) -> bool {
        !is_loader_or_framework_root(content_root)
    }

    fn resolve_deploy_root(&self, install_path: &Path, relative: &Path) -> Result<PathBuf> {
        let normalized = normalize_relative(relative);
        let components = path_components_lower(&normalized);
        if components.is_empty() {
            return Ok(install_path.to_path_buf());
        }

        let first = components[0].as_str();

        if first == "dmf" {
            return Ok(install_path.join("mods").join(&normalized));
        }

        if DARKTIDE_ROOT_DIRS.iter().any(|r| *r == first) {
            return Ok(join_canonical(install_path, &normalized, &components));
        }

        // Loose Mod Loader root files (e.g. toggle_darktide_mods.bat).
        if components.len() == 1 {
            return Ok(install_path.join(&normalized));
        }

        Ok(install_path.join("mods").join(&normalized))
    }

    fn after_deploy(
        &self,
        install_path: &Path,
        enabled_mod_folders: &[String],
    ) -> Result<Vec<String>> {
        let mut warnings = Vec::new();
        write_mod_load_order(install_path, enabled_mod_folders)?;
        match run_darktide_patcher(install_path) {
            Ok(None) => {}
            Ok(Some(msg)) => warnings.push(msg),
            Err(e) => warnings.push(format!("Darktide patcher failed: {e:#}")),
        }
        Ok(warnings)
    }
}

fn is_loader_or_framework_root(content_root: &Path) -> bool {
    if content_root.join("toggle_darktide_mods.bat").is_file() {
        return true;
    }
    for name in DARKTIDE_ROOT_DIRS {
        if content_root.join(name).is_dir() {
            return true;
        }
    }
    // DMF ships as a preserved `dmf/` directory at the staging root.
    if content_root.join("dmf").is_dir() {
        return true;
    }
    // After peel is skipped, content_root itself may be the `dmf` folder.
    if content_root
        .file_name()
        .and_then(|n| n.to_str())
        .is_some_and(|n| n.eq_ignore_ascii_case("dmf"))
    {
        return true;
    }
    false
}

pub fn write_mod_load_order(install_path: &Path, enabled_mod_folders: &[String]) -> Result<()> {
    let mods_dir = install_path.join("mods");
    std::fs::create_dir_all(&mods_dir)
        .with_context(|| format!("create mods dir {}", mods_dir.display()))?;
    let path = mods_dir.join("mod_load_order.txt");

    let mut body = String::from(
        "-- Auto-generated by Nexus Manager. Do not list dmf or the Mod Loader here.\n",
    );
    for name in enabled_mod_folders {
        if DARKTIDE_LOAD_ORDER_EXCLUDE
            .iter()
            .any(|ex| name.eq_ignore_ascii_case(ex))
        {
            continue;
        }
        if name.trim().is_empty() {
            continue;
        }
        body.push_str(name);
        body.push('\n');
    }
    std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

/// Resolve which patcher binary to run (does not spawn). Public for tests.
pub fn resolve_patcher_command(install_path: &Path) -> Option<PatcherCommand> {
    let tools = install_path.join("tools");
    let exe = tools.join("dtkit-patch.exe");
    let bare = tools.join("dtkit-patch");

    #[cfg(windows)]
    {
        if exe.is_file() {
            return Some(PatcherCommand::Native(exe));
        }
        if bare.is_file() {
            return Some(PatcherCommand::Native(bare));
        }
        return None;
    }

    #[cfg(not(windows))]
    {
        if bare.is_file() && is_likely_executable(&bare) {
            return Some(PatcherCommand::Native(bare));
        }
        if exe.is_file() && wine_available() {
            return Some(PatcherCommand::Wine(exe));
        }
        if bare.is_file() && wine_available() {
            // Windows PE without +x sometimes ships as bare name
            return Some(PatcherCommand::Wine(bare));
        }
        if bare.is_file() {
            return Some(PatcherCommand::Native(bare));
        }
        None
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PatcherCommand {
    Native(PathBuf),
    Wine(PathBuf),
}

#[cfg(unix)]
fn is_likely_executable(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    std::fs::metadata(path)
        .map(|m| m.permissions().mode() & 0o111 != 0)
        .unwrap_or(false)
}

#[cfg(not(windows))]
fn wine_available() -> bool {
    Command::new("wine")
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn bundle_already_patched(install_path: &Path) -> bool {
    let db = install_path.join("bundle").join("bundle_database.data");
    let Ok(bytes) = std::fs::read(&db) else {
        return false;
    };
    bytes
        .windows(PATCH_MARKER.len())
        .any(|w| w == PATCH_MARKER)
}

/// Run `dtkit-patch --patch bundle`. Returns Ok(Some(warning)) for soft issues.
pub fn run_darktide_patcher(install_path: &Path) -> Result<Option<String>> {
    if bundle_already_patched(install_path) {
        log::info!("Darktide bundle already patched; skipping dtkit-patch");
        return Ok(None);
    }

    let Some(cmd) = resolve_patcher_command(install_path) else {
        return Ok(Some(
            "Darktide Mod Loader patcher (tools/dtkit-patch) not found. Install the Mod Loader, then deploy again."
                .into(),
        ));
    };

    let mut command = match &cmd {
        PatcherCommand::Native(bin) => {
            let mut c = Command::new(bin);
            c.arg("--patch").arg("bundle");
            c
        }
        PatcherCommand::Wine(bin) => {
            let mut c = Command::new("wine");
            c.arg(bin).arg("--patch").arg("bundle");
            c
        }
    };
    command
        .current_dir(install_path)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    let mut child = command
        .spawn()
        .with_context(|| format!("spawn Darktide patcher from {}", install_path.display()))?;

    let mut stdout_pipe = child.stdout.take();
    let mut stderr_pipe = child.stderr.take();
    let stdout_thread = std::thread::spawn(move || {
        let mut buf = String::new();
        if let Some(ref mut out) = stdout_pipe {
            use std::io::Read;
            let _ = out.read_to_string(&mut buf);
        }
        buf
    });
    let stderr_thread = std::thread::spawn(move || {
        let mut buf = String::new();
        if let Some(ref mut err) = stderr_pipe {
            use std::io::Read;
            let _ = err.read_to_string(&mut buf);
        }
        buf
    });

    let deadline = std::time::Instant::now() + PATCHER_TIMEOUT;
    let status = loop {
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) => {
                if std::time::Instant::now() >= deadline {
                    let _ = child.kill();
                    let _ = child.wait();
                    let _ = stdout_thread.join();
                    let _ = stderr_thread.join();
                    return Ok(Some(
                        "Darktide patcher timed out after 60s (stuck wine/prefix?).".into(),
                    ));
                }
                std::thread::sleep(Duration::from_millis(100));
            }
            Err(e) => return Err(e).context("wait for Darktide patcher"),
        }
    };

    let stdout = stdout_thread.join().unwrap_or_default();
    let stderr = stderr_thread.join().unwrap_or_default();
    if status.success() {
        log::info!("Darktide patcher ok: {stdout}{stderr}");
        return Ok(None);
    }
    let detail = format!("{stdout}{stderr}").trim().to_string();
    let msg = if detail.is_empty() {
        format!("dtkit-patch exited with {status}")
    } else {
        format!("dtkit-patch exited with {status}: {detail}")
    };
    Ok(Some(msg))
}

fn path_components_lower(path: &Path) -> Vec<String> {
    path.components()
        .filter_map(|c| match c {
            Component::Normal(s) => Some(s.to_string_lossy().to_lowercase()),
            _ => None,
        })
        .collect()
}

fn join_canonical(install_path: &Path, normalized: &Path, lower_components: &[String]) -> PathBuf {
    let mut out = install_path.to_path_buf();
    let originals: Vec<_> = normalized
        .components()
        .filter_map(|c| match c {
            Component::Normal(s) => Some(s.to_string_lossy().into_owned()),
            _ => None,
        })
        .collect();

    for (i, lower) in lower_components.iter().enumerate() {
        if i == 0 && DARKTIDE_ROOT_DIRS.iter().any(|r| *r == lower.as_str()) {
            out.push(lower.as_str());
        } else if let Some(orig) = originals.get(i) {
            out.push(orig);
        } else {
            out.push(lower.as_str());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::games::GamePlugin;

    fn plugin() -> Warhammer40kDarktidePlugin {
        Warhammer40kDarktidePlugin
    }

    #[test]
    fn resolves_loader_roots() {
        let install = Path::new("/game");
        let p = plugin();
        assert_eq!(
            p.resolve_deploy_root(install, Path::new("tools/dtkit-patch.exe"))
                .unwrap(),
            PathBuf::from("/game/tools/dtkit-patch.exe")
        );
        assert_eq!(
            p.resolve_deploy_root(install, Path::new("binaries/mod_loader"))
                .unwrap(),
            PathBuf::from("/game/binaries/mod_loader")
        );
        assert_eq!(
            p.resolve_deploy_root(install, Path::new("bundle/9ba626afa44a3aa3.patch_999"))
                .unwrap(),
            PathBuf::from("/game/bundle/9ba626afa44a3aa3.patch_999")
        );
        assert_eq!(
            p.resolve_deploy_root(install, Path::new("mods/mod_load_order.txt"))
                .unwrap(),
            PathBuf::from("/game/mods/mod_load_order.txt")
        );
    }

    #[test]
    fn dmf_lands_under_mods() {
        let install = Path::new("/game");
        let p = plugin();
        assert_eq!(
            p.resolve_deploy_root(install, Path::new("dmf/dmf.lua"))
                .unwrap(),
            PathBuf::from("/game/mods/dmf/dmf.lua")
        );
    }

    #[test]
    fn bat_at_root() {
        let install = Path::new("/game");
        let p = plugin();
        assert_eq!(
            p.resolve_deploy_root(install, Path::new("toggle_darktide_mods.bat"))
                .unwrap(),
            PathBuf::from("/game/toggle_darktide_mods.bat")
        );
    }

    #[test]
    fn wrapped_mod_under_mods() {
        let install = Path::new("/game");
        let p = plugin();
        assert_eq!(
            p.resolve_deploy_root(install, Path::new("scoreboard/scripts/mods/scoreboard/scoreboard.lua"))
                .unwrap(),
            PathBuf::from("/game/mods/scoreboard/scripts/mods/scoreboard/scoreboard.lua")
        );
    }

    #[test]
    fn wrap_detection() {
        let loader = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(loader.path().join("tools")).unwrap();
        std::fs::write(loader.path().join("toggle_darktide_mods.bat"), b"x").unwrap();
        assert!(!plugin().should_wrap_as_mod_folder(loader.path()));

        let dmf = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dmf.path().join("dmf")).unwrap();
        assert!(!plugin().should_wrap_as_mod_folder(dmf.path()));

        let normal = tempfile::tempdir().unwrap();
        std::fs::write(normal.path().join("scoreboard.mod"), b"x").unwrap();
        assert!(plugin().should_wrap_as_mod_folder(normal.path()));
    }

    #[test]
    fn load_order_excludes_dmf_and_writes_enabled() {
        let install = tempfile::tempdir().unwrap();
        write_mod_load_order(
            install.path(),
            &["scoreboard".into(), "dmf".into(), "healthbars".into()],
        )
        .unwrap();
        let text = std::fs::read_to_string(install.path().join("mods/mod_load_order.txt")).unwrap();
        assert!(text.contains("scoreboard\n"));
        assert!(text.contains("healthbars\n"));
        assert!(!text.lines().any(|l| l.trim() == "dmf"));
    }

    #[test]
    fn resolve_patcher_prefers_exe_on_windows_layout() {
        let install = tempfile::tempdir().unwrap();
        let tools = install.path().join("tools");
        std::fs::create_dir_all(&tools).unwrap();
        std::fs::write(tools.join("dtkit-patch.exe"), b"fake").unwrap();
        let cmd = resolve_patcher_command(install.path());
        #[cfg(windows)]
        {
            assert!(matches!(cmd, Some(PatcherCommand::Native(p)) if p.ends_with("dtkit-patch.exe")));
        }
        #[cfg(not(windows))]
        {
            // Without wine, may be None or Wine depending on environment; with only .exe and no wine → None
            // Ensure it does not panic and prefers wine path when wine exists.
            if wine_available() {
                assert!(matches!(cmd, Some(PatcherCommand::Wine(_))));
            } else {
                assert!(cmd.is_none());
            }
        }
    }

    #[test]
    fn missing_patcher_returns_warning() {
        let install = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(install.path().join("bundle")).unwrap();
        let warn = run_darktide_patcher(install.path()).unwrap();
        assert!(warn.is_some());
        assert!(warn.unwrap().contains("dtkit-patch"));
    }

    #[test]
    fn already_patched_skips_spawn() {
        let install = tempfile::tempdir().unwrap();
        let bundle = install.path().join("bundle");
        std::fs::create_dir_all(&bundle).unwrap();
        std::fs::write(bundle.join("bundle_database.data"), b"xxxpatch_999yyy").unwrap();
        let warn = run_darktide_patcher(install.path()).unwrap();
        assert!(warn.is_none());
    }
}
