//! The Witcher 3: Wild Hunt (REDengine 3).
//!
//! Typical layout:
//! ```text
//! <Install>/mods/<ModName>/content/...
//! <Install>/dlc/<DlcName>/...
//! <Install>/bin/x64/...
//! Documents/The Witcher 3/mods.settings
//! ```

use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result};

use super::{content_folder_wrap_name, normalize_relative, GamePlugin, GamePluginInfo};

const STEAM_APP_ID: &str = "292030";

pub const WITCHER3_ROOT_DIRS: &[&str] = &["mods", "dlc", "bin", "content"];

pub struct Witcher3Plugin;

impl GamePlugin for Witcher3Plugin {
    fn info(&self) -> GamePluginInfo {
        GamePluginInfo {
            id: "witcher3",
            display_name: "The Witcher 3",
            nexus_domain: "witcher3",
            match_names: &["witcher 3", "witcher3", "the witcher 3"],
        }
    }

    fn prefers_mod_folder(&self) -> bool {
        false
    }

    fn preserve_staging_root_names(&self) -> &[&str] {
        WITCHER3_ROOT_DIRS
    }

    fn should_wrap_as_mod_folder(&self, content_root: &Path) -> bool {
        looks_like_tw3_mod_pack(content_root)
    }

    fn wrap_mod_folder_name(&self, content_root: &Path, staged_name: &str) -> String {
        content_folder_wrap_name(content_root, staged_name)
    }

    fn resolve_deploy_root(&self, install_path: &Path, relative: &Path) -> Result<PathBuf> {
        let normalized = normalize_relative(relative);
        let components = path_components_lower(&normalized);
        if components.is_empty() {
            return Ok(install_path.join("mods"));
        }

        let first = components[0].as_str();
        if WITCHER3_ROOT_DIRS.iter().any(|r| *r == first) {
            return Ok(join_canonical(install_path, &normalized, &components));
        }

        Ok(install_path.join("mods").join(&normalized))
    }

    fn after_deploy(
        &self,
        install_path: &Path,
        enabled_mod_folders: &[String],
    ) -> Result<Vec<String>> {
        write_mods_settings(install_path, enabled_mod_folders)?;
        Ok(Vec::new())
    }
}

fn looks_like_tw3_mod_pack(content_root: &Path) -> bool {
    if content_root.join("mods").is_dir()
        || content_root.join("dlc").is_dir()
        || content_root.join("bin").is_dir()
    {
        return false;
    }
    content_root.join("content").is_dir()
}

fn write_mods_settings(install_path: &Path, enabled_mod_folders: &[String]) -> Result<()> {
    let Some(dir) = mods_settings_dir(install_path) else {
        return Ok(());
    };
    std::fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;
    let path = dir.join("mods.settings");
    let mut body = String::from("; Auto-generated by Emperor Mod Manager.\n");
    for (i, name) in enabled_mod_folders.iter().enumerate() {
        let trimmed = name.trim();
        if trimmed.is_empty() {
            continue;
        }
        let priority = i + 1;
        body.push('[');
        body.push_str(trimmed);
        body.push_str("]\nEnabled=1\nPriority=");
        body.push_str(&priority.to_string());
        body.push('\n');
    }
    std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn mods_settings_dir(install_path: &Path) -> Option<PathBuf> {
    super::user_data::documents_dir(install_path, STEAM_APP_ID).map(|d| d.join("The Witcher 3"))
}

fn path_components_lower(path: &Path) -> Vec<String> {
    path.components()
        .filter_map(|c| match c {
            Component::Normal(s) => Some(s.to_string_lossy().to_lowercase()),
            _ => None,
        })
        .collect()
}

fn join_canonical(install_path: &Path, normalized: &Path, lower_components: &[String]) -> PathBuf {
    let mut out = install_path.to_path_buf();
    let originals: Vec<_> = normalized
        .components()
        .filter_map(|c| match c {
            Component::Normal(s) => Some(s.to_string_lossy().into_owned()),
            _ => None,
        })
        .collect();

    for (i, lower) in lower_components.iter().enumerate() {
        if i == 0 && WITCHER3_ROOT_DIRS.iter().any(|r| *r == lower.as_str()) {
            out.push(lower.as_str());
        } else if let Some(orig) = originals.get(i) {
            out.push(orig);
        } else {
            out.push(lower.as_str());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn plugin() -> Witcher3Plugin {
        Witcher3Plugin
    }

    #[test]
    fn bin_stays_at_install_root() {
        let dest = plugin()
            .resolve_deploy_root(Path::new("/game"), Path::new("bin/x64/dinput8.dll"))
            .unwrap();
        assert_eq!(dest, PathBuf::from("/game/bin/x64/dinput8.dll"));
    }

    #[test]
    fn content_packs_wrap_under_mods() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("content").join("scripts")).unwrap();
        assert!(plugin().should_wrap_as_mod_folder(dir.path()));
        let dest = plugin()
            .resolve_deploy_root(Path::new("/game"), Path::new("modFoo/content/scripts/a.ws"))
            .unwrap();
        assert_eq!(
            dest,
            PathBuf::from("/game/mods/modFoo/content/scripts/a.ws")
        );
    }

    #[test]
    fn does_not_wrap_bin_or_dlc_roots() {
        let bin = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(bin.path().join("bin").join("x64")).unwrap();
        std::fs::create_dir_all(bin.path().join("content")).unwrap();
        assert!(!plugin().should_wrap_as_mod_folder(bin.path()));
    }

    #[test]
    fn writes_mods_settings_from_load_order() {
        let tmp = tempfile::tempdir().unwrap();
        let steamapps = tmp.path().join("steamapps");
        let install = steamapps.join("common").join("The Witcher 3");
        let docs = steamapps
            .join("compatdata")
            .join(STEAM_APP_ID)
            .join("pfx")
            .join("drive_c")
            .join("users")
            .join("steamuser")
            .join("Documents");
        std::fs::create_dir_all(&install).unwrap();
        std::fs::create_dir_all(&docs).unwrap();

        plugin()
            .after_deploy(&install, &["modA".into(), "modB".into()])
            .unwrap();
        let raw =
            std::fs::read_to_string(docs.join("The Witcher 3").join("mods.settings")).unwrap();
        assert!(raw.contains("[modA]"));
        assert!(raw.contains("Priority=1"));
        assert!(raw.contains("[modB]"));
        assert!(raw.contains("Priority=2"));
    }
}
